# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VTOTl2wIDtpohAiJC9-Vp365fWdRTNwB
"""

from setuptools import setup, find_packages

setup(
    name="transformer_lib",             # 라이브러리 호출 이름
    version="0.1",
    packages=find_packages(),
    install_requires=[                  # 의존성 라이브러리
        "tensorflow>=2.0",
        "numpy",
    ],
)